export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of Tom and Jerry in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    'a realistic HD art by Van Gogh of a starry night sky over a field of sunflowers',
    'a surrealist landscape in the style of Picasso, with melted clocks and floating buildings',
    'a group of dinosaurs playing volleybool on a beach, in the style of Jurassic Park',
    'a steampunk robot playing the piano, in the style of Tesla',
    'a photorealistic painting of an alien spaceship landing on Earth',
    'a hyperrealistic digital painting of a wormhole, with two galaxies on either side',
    'a Renaissance-era painting of a mad scientist creating a monster',
    'a cyberpunk cityscape with flying unicorns and dragons',
    'a fantasy painting of a group of dwarves mining for gold',
    'a realistic 3D rendering of a human heart, with all the blood vessels and chambers visible',
    'a microscopic view of a DNA molecule, with all the individual atoms and molecules visible',
    'a cross-section of a Saturn V rocket, with all the engines and fuel tanks visible',
    'a close-up of a human eye, with all the intricate blood vessels and nerves visible',
    "a photorealistic painting of a dewdrop on a spider's web",
    'realistic HD art by Monet of a giant octopus swimming through a field of flowers',
    'surrealist portrait of a cat with a human face, in the style of Dali',
    'a group of astronauts playing basketball on the moon, in the style of NASA',
    'a steampunk city floating in the clouds, in the style of Jules Verne',
    'a photorealistic painting of a dragon flying over a medieval castle',
    'a hyperrealistic digital painting of a black hole, with stars and nebulae in the background',
    'a Renaissance-era painting of a robot playing the violin',
    'a cyberpunk cityscape with neon lights and flying cars',
    'a fantasy painting of a group of elves and fairies dancing in a forest',
    'a realistic 3D rendering of a human brain, with all the neurons and connections visible',
    'a microscopic view of a virus, with all the individual atoms and molecules visible',
    'a cross-section of a volcano, with the magma flowing inside',
    "a close-up of a butterfly's wing, with all the intricate scales and patterns visible",
    'a photorealistic painting of a snowflake, with all the individual ice crystals visible',
    'realistic HD art by Beeple of a giant robot exploring a Martian desert',
    'cyberpunk portrait of a woman with glowing eyes and cybernetic implants',
    'trippy psychedelic landscape with melting mountains and floating trees',
    'low-poly art of a futuristic cityscape with flying cars and neon lights',
    'abstract digital painting of a human face made up of swirling colors and shapes',
    'realistic 3D rendering of a quantum computer, with all the individual qubits visible',
    'generative art of a neural network learning to see the world',
    'AI-generated portrait of a person who does not exist',
    'voxel art of a medieval castle under attack by a dragon',
    'isometric art of a bustling city with people going about their daily lives',
    'pixel art of a retro video game character jumping over obstacles',
    'ASCII art of a famous painting, such as the Mona Lisa or Starry Night',
];